# Default values for attestation-controller.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

podAnnotations: {}
podLabels: {}

image:
  pullPolicy: IfNotPresent
  # registry: artifacts.developer.gov.bc.ca/github-docker-remote
  # repository: bcgov/mobile-attestation-vc-controller/controller
  registry: artifacts.developer.gov.bc.ca/docker-remote
  repository: grafana/loki
  # Overrides the image tag whose default is the chart appVersion.
  tag: "latest"

imagePullSecrets:
  - name: artifactory-creds

env:
  LOKI_CONFIG_PATH: "/etc/loki/config.yaml"

resources:
  requests:
    memory: 64Mi
    cpu: 10m
  limits:
    memory: 92Mi
    cpu: 100m

persistentVolumeClaim:
  mountPath: /data
  storageSize: 1Gi
  storageClass: netapp-file-standard
  annotations:
    helm.sh/resource-policy: keep

service:
  httpPort: 3100
  grpcPort: 9096

route:
  host: ""
  annotations:
    haproxy.router.openshift.io/timeout: 60s

autoscaling:
  enabled: false
#   minReplicas: 1
#   maxReplicas: 5
#   targetCPUUtilizationPercentage: 80

# serviceAccount:
#   # Specifies whether a service account should be created
#   create: true
#   # Automatically mount a ServiceAccount's API credentials?
#   automount: true
#   # Annotations to add to the service account
#   annotations: {}
#   # The name of the service account to use.
#   # If not set and create is true, a name is generated using the fullname template
#   name: ""

# Additional volumes on the output Deployment definition.
volumes: []
# - name: foo
#   secret:
#     secretName: mysecret
#     optional: false

# Additional volumeMounts on the output Deployment definition.
volumeMounts: []
# - name: foo
#   mountPath: "/etc/foo"
#   readOnly: true

