name: Check for early exit
description: |
  This action checks for changes in specific directories and
  exits early if there are none

runs:
  using: composite
  steps:
    - name: Check location of changed files
      shell: bash
      run: |
        git branch

        echo "a"

        pwd
        echo "b"

        git diff --name-only origin/main..HEAD
        echo "c"

        git diff --name-only origin/main..HEAD | grep -E '^(app/.*)|(.yarn/.*)|(.github/workflows/.*)'
        echo "d"

        git diff --name-only origin/main..HEAD | grep -E '^(app/.*)|(.yarn/.*)|(.github/workflows/.*)' | wc -l
        echo "e"

        change_count=$(git diff --name-only origin/main..HEAD | grep -E '^(app/.*)|(.yarn/.*)|(.github/workflows/.*)' | wc -l)
        echo "$change_count files changed in app, .yarn, or .github/workflows"
        if [ $change_count -gt 0 ]; then
          # A result greater than 0 means there are changes
          # in the specified directories.
          echo "result=false" >> $GITHUB_OUTPUT
        else
          echo "result=true" >> $GITHUB_OUTPUT
        fi
