name: Check for early exit
description: |
  This action checks for changes in specific directories and
  exits early if there are none

runs:
  using: composite
  steps:
    - name: Check location of changed files
      shell: bash
      run: |
        set -x

        if [ "${GITHUB_REF_NAME}" = "main" ]; then 
          # On main branch, compare with the previous
          # commit otherwise (for PRs) compare with the
          # current commit.
          parent_ref="${GITHUB_REF_NAME:-main}^"
          child_ref="${GITHUB_SHA}"
        else
          # On PRs, compare with the base branch.
          parent_ref="origin/${GITHUB_BASE_REF:-main}"
          child_ref="HEAD"
        fi

        echo "Comparing ${parent_ref} with ${child_ref}"

        diff_output=$(git diff --name-only ${parent_ref}..${child_ref})
        # change_count=$(echo "$diff_output" | grep -E '^(app/.*)|(.yarn/.*)|(.github/workflows/.*)' | wc -l | awk '{$1=$1};1' || true)
        change_count=$(echo "$diff_output" | grep -E '^(blarb/.*)' | wc -l | awk '{$1=$1};1' || true)

        echo "$change_count files changed in app, .yarn, or .github/workflows"

        if [ $change_count -gt 0 ]; then
          # A result greater than 0 means there are changes
          # in the specified directories.
          echo "result=true" >> $GITHUB_OUTPUT
        else
          echo "result=false" >> $GITHUB_OUTPUT
        fi
