---
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: {{ include "loki.fullname" . }}
  labels: {{- include "loki.labels" . | nindent 4 }}
  annotations: {{- toYaml .Values.route.annotations | nindent 4 }}
spec:
  podSelector:
    matchLabels: {{- include "loki.selectorLabels" . | nindent 6 }}
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              network.openshift.io/policy-group: ingress
  policyTypes:
    - Ingress
