---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "loki.fullname" . }}-data
  labels: {{- include "loki.labels" . | nindent 4 }}
  annotations: {{- toYaml .Values.persistentVolumeClaim.annotations | nindent 4 }}
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: {{ .Values.persistentVolumeClaim.storageClass }}
  resources:
    requests:
      storage: {{ .Values.persistentVolumeClaim.storageSize }}