---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "loki.fullname" . }}
  labels: {{- include "loki.labels" . | nindent 4 }}
spec:
  ports:
    - port: {{ .Values.service.httpPort }}
      targetPort: {{ .Values.service.httpPort }}
      protocol: TCP
      name: http
    - port: {{ .Values.service.grpcPort }}
      targetPort: {{ .Values.service.grpcPort }}
      protocol: TCP
      name: grpc
  selector: {{- include "loki.selectorLabels" . | nindent 4 }}
