---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "logstack.fullname" . }}-loki-data
  labels: {{- include "logstack.labels" . | nindent 4 }}
  annotations: {{- toYaml .Values.pvc.loki.annotations | nindent 4 }}
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: {{ .Values.pvc.loki.storageClass }}
  resources:
    requests:
      storage: {{ .Values.pvc.loki.storageSize }}
